### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by parkseongwon26** [OpenMotionLab/MotionGPT#52]
python demo.py --cfg ./configs/config_h3d_stage3.yaml --example ./demos/t2m.txt

FileNotFoundError: [Errno 2] No such file or directory: 'deps/t2m/t2m\\VQVAEV3_CB1024_CMT_H1024_NRES3\\meta\\mean.npy'

But, I have this file.
![image](https://github.com/OpenMotionLab/MotionGPT/assets/145101606/2e350ace-70fb-43b8-b1ca-a93d20559000)

**Comment by Cakeyan** [comment]
+1, it is wierd

**Comment by franknoh** [comment]
I fixed it by changing the paths in `mGPT/data/HumanML3D.py`
```python
        # Mean and std of the dataset
        dis_data_root = pjoin(cfg.DATASET.HUMANML3D.MEAN_STD_PATH, 't2m/t2m', "VQVAEV3_CB1024_CMT_H1024_NRES3", "meta")
        self.hparams.mean = np.load(pjoin(dis_data_root, "mean.npy"))
        self.hparams.std = np.load(pjoin(dis_data_root, "std.npy"))
        
        # Mean and std for fair evaluation
        dis_data_root_eval = pjoin(cfg.DATASET.HUMANML3D.MEAN_STD_PATH, 't2m/t2m', "Comp_v6_KLD01", "meta")
        self.hparams.mean_eval = np.load(pjoin(dis_data_root_eval, "mean.npy"))
        self.hparams.std_eval = np.load(pjoin(dis_data_root_eval, "std.npy"))
```

and in `configs/assets.yaml`
```yaml
DATASET:
  TASK_ROOT: deps/mGPT_instructions
  SMPL_PATH: deps/smpl
  TRANSFORM_PATH: deps/transforms/
  WORD_VERTILIZER_PATH: deps/t2m/glove/
```

hope it helps!
